# Site details
title: Field Guides for Ecologists
subtitle: Crowd-sourced notes on all things<br>computational and quantitative in ecological research
acronym: FGE

# URLS
licenseurl: "https://github.com/BES-QSIG/fge/blob/master/LICENSE"
baseurl: "/fge"
docurl: "https://github.com/BES-QSIG/docs/blob/master/"
imgurl: "https://raw.githubusercontent.com/BES-QSIG/docs/master/img"
url: "http://bes-qsig.github.io"

# Permalinks
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/

# Social
twitter_username: BES_QE_SIG
github_username:  BES-QSIG
email: quantitative@britishecologicalsociety.org

# Build settings (GHFM)
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
               "strikethrough", "superscript", "with_toc_data", "tables"]

# Image settings
cover: /img/cover.jpg
icon: favicon.ico

# Menu settings
menu:
  - title:        Home
    url:          /

  - title:        Index
    url:          /guides

  - title:        News
    url:          /news

  - title:        Contributors
    url:          /contributors

# 'Collections' settings
exclude: ['_docs/README.md', '_docs/LICENSE', 'build.py']
collections:
  docs:
    output: true
